window.DONISHEF_MENU_SEED = [
  {id:1,name:'Самаркандский плов',cat:'Плов',price:550,weight:'450 г',desc:'Рассыпчатый рис с мясом, морковью и восточными специями',servingNote:'К ПЛОВУ БЕСПЛАТНО: ЛЕПЁШКА И САЛАТ ИЗ КАПУСТЫ (50 Г)',tag:'ХИТ',image:"assets/optimized/restaurant-plov-hero.webp",photo:true},
  {id:2,name:'Баранья ножка',cat:'Вторые блюда',price:700,weight:'350 г',desc:'Томлёная баранья ножка с нежным пюре',image:"assets/optimized/codex-clipboard-4f0581d2-d360-43f4-b783-721bb5d96eea.webp"},
  {id:3,name:'Курутоб',cat:'Вторые блюда',price:600,weight:'600 г',desc:'Таджикское блюдо из лепёшки фатир с курутом, зеленью, овощами и мясом',recipe:'Курут — сушёный солёный кисломолочный сыр — размачивают в воде до соуса. Им пропитывают кусочки лепёшки фатир и добавляют зелень и овощи. В версии DoniШеф блюдо подают с мясом.',image:"assets/optimized/codex-clipboard-93cab4db-966f-4519-8c7b-c31c1e08551d.webp"},
  {id:4,name:'Форель с фри',cat:'Вторые блюда',price:800,weight:'350 г',desc:'Форель на гриле, картофель и свежий салат',image:"assets/optimized/codex-clipboard-9942fb19-acb9-433f-9987-922204aa2484.webp"},
  {id:5,name:'Лагман',cat:'Первые блюда',price:500,weight:'400 г',desc:'Сытный суп с лапшой и мясом',image:"assets/optimized/restaurant-lagman.webp",photo:true},
  {id:6,name:'Наггетсы с фри',cat:'Детское меню',price:500,weight:'250 г',desc:'Куриные наггетсы с картофелем фри',image:"assets/optimized/restaurant-kids.webp",photo:true},
  {id:7,name:'Казан-кебаб · говядина',cat:'Вторые блюда',price:600,weight:'400 г',desc:'Нежная говядина с картофелем по-восточному',image:"assets/optimized/codex-clipboard-212eb699-02ea-4007-a619-1a4bea8b73d0.webp"},
  {id:8,name:'Казан-кебаб · баранина',cat:'Вторые блюда',price:650,weight:'400 г',desc:'Баранина, картофель и ароматный лук',image:"assets/optimized/codex-clipboard-b499d369-0ca4-49ef-a07e-b6d30f356a8c.webp"},
  {id:9,name:'Манты',cat:'Вторые блюда',price:550,weight:'300 г',desc:'Домашние манты со сметаной',tag:'ПОПУЛЯРНОЕ',image:"assets/optimized/codex-clipboard-1ba49306-bbdf-42a0-9c37-b2e30605f665.webp"},
  {id:10,name:'Чахохбили с пюре',cat:'Вторые блюда',price:550,weight:'400 г',desc:'Курица в насыщенном соусе с пюре',image:"assets/optimized/codex-clipboard-5c6b655c-e1c6-4541-98d1-32a0fc8fefa6.webp"},
  {id:11,name:'Котлеты с пюре',cat:'Вторые блюда',price:550,weight:'350 г',desc:'Домашние котлеты и картофельное пюре',image:"assets/optimized/codex-clipboard-7227da99-1517-4677-8ea2-65a518cf4061.webp"},
  {id:12,name:'Мастава',cat:'Первые блюда',price:500,weight:'400 г',desc:'Ароматный томатный суп с мясом',image:"assets/optimized/restaurant-shurpa.webp",photo:true},
  {id:15,name:'Пельмени',cat:'Первые блюда',price:500,weight:'350 г',desc:'Пельмени в прозрачном бульоне',image:"assets/optimized/codex-clipboard-812e52f6-a1bb-4226-adb6-409bc1cd29c4.webp"},
  {id:16,name:'Чечевичный суп',cat:'Первые блюда',price:300,weight:'300 г',desc:'Нежный крем-суп с хрустящими гренками',image:"assets/optimized/codex-clipboard-cdbfd1aa-65ed-4d00-858f-ddca54f41f9d.webp"},
  {id:17,name:'Плов от «Дони»',cat:'Плов',price:600,weight:'450 г',desc:'Фирменный плов DoniШеф с мясом и восточными специями',servingNote:'К ПЛОВУ БЕСПЛАТНО: ЛЕПЁШКА И САЛАТ ИЗ КАПУСТЫ (50 Г)',tag:'ФИРМЕННОЕ',image:"assets/optimized/codex-clipboard-d1e7e094-41d7-4c46-91b1-37643d621b62.webp"},
  {id:27,name:'Самаркандский плов · 2 порции',cat:'Плов',price:1200,weight:'2 порции',desc:'Фирменный плов DoniШеф с мясом и восточными специями — две порции',servingNote:'К ПЛОВУ БЕСПЛАТНО: ЛЕПЁШКА И САЛАТ ИЗ КАПУСТЫ (50 Г)',image:"assets/optimized/restaurant-plov-bowl.webp",photo:true},
  {id:20,name:'Картофель фри',cat:'Гарниры',price:150,weight:'150 г',desc:'Хрустящий золотистый картофель',image:"assets/optimized/codex-clipboard-76e1df82-704e-49ea-90e4-d75cc3bba09b.webp"},
  {id:21,name:'Салат с баклажанами',cat:'Салаты',price:550,weight:'250 г',desc:'Овощи, баклажаны и хрустящий сыр',image:"assets/optimized/restaurant-salad.webp",photo:true},
  {id:22,name:'Цезарь с курицей',cat:'Салаты',price:450,weight:'250 г',desc:'Куриное филе, салат, томаты и пармезан',image:"assets/optimized/codex-clipboard-13c0ebca-21fc-4387-b8a7-fe8ab47c74d5.webp"},
  {id:23,name:'Самаркандский плов · полпорции',cat:'Полпорции',price:350,weight:'½ порции',desc:'Половина порции Самаркандского плова с мясом и восточными специями',servingNote:'К ПЛОВУ БЕСПЛАТНО: ЛЕПЁШКА И САЛАТ ИЗ КАПУСТЫ (50 Г)',image:"assets/optimized/half-samarkand-plov.webp",photo:true},
  {id:24,name:'Бешбармак',cat:'Вторые блюда',price:800,weight:'Порция',desc:'Бешбармак с мясом, домашней лапшой и луком',image:"assets/optimized/beshbarmak.webp",photo:true},
  {id:25,name:'Кёфта с фри',cat:'Вторые блюда',price:700,weight:'Порция',desc:'Кёфта на гриле с картофелем фри, зеленью и соусом',image:"assets/optimized/kofta-fries.webp",photo:true},
  {id:26,name:'Шурпа · говядина',cat:'Первые блюда',price:500,weight:'400 г',desc:'Наваристый бульон с говядиной и овощами',image:"assets/optimized/beef-shurpa.webp",photo:true},
  {id:28,name:'Лагман · полпорции',cat:'Полпорции',price:350,weight:'½ порции',desc:'Половина порции лагмана с лапшой и мясом',image:"assets/optimized/restaurant-lagman.webp",photo:true},
  {id:29,name:'Мастава · полпорции',cat:'Полпорции',price:350,weight:'½ порции',desc:'Половина порции ароматной маставы с мясом',image:"assets/optimized/restaurant-shurpa.webp",photo:true},
  {id:30,name:'Пельмени · полпорции',cat:'Полпорции',price:350,weight:'½ порции',desc:'Половина порции пельменей в прозрачном бульоне',image:"assets/optimized/codex-clipboard-812e52f6-a1bb-4226-adb6-409bc1cd29c4.webp"},
  {id:31,name:'Шурпа · говядина · полпорции',cat:'Полпорции',price:350,weight:'½ порции',desc:'Половина порции наваристой шурпы с говядиной и овощами',image:"assets/optimized/beef-shurpa.webp",photo:true},
  {id:32,name:'Жареный лагман',cat:'Вторые блюда',price:600,weight:'Порция',desc:'Лапша, обжаренная с мясом и овощами',image:"assets/optimized/fried-lagman.webp",photo:true},
  {id:33,name:'Куриные крылышки на мангале',cat:'Мангал',price:450,weight:'Порция',desc:'Куриные крылышки, приготовленные на мангале',image:"assets/optimized/shashlik-chicken-wings.webp",photo:true},
  {id:34,name:'Шашлык на мангале',cat:'Мангал',price:500,weight:'Порция',desc:'Шашлык с луком и соусом',image:"assets/optimized/shashlik-meat.webp",photo:true},
  {id:35,name:'Картофель на мангале',cat:'Мангал',price:300,weight:'Порция',desc:'Картофель, приготовленный на мангале',image:"assets/optimized/grill-potatoes.webp",photo:true},
  {id:36,name:'Бараньи рёбрышки',cat:'Мангал',price:500,weight:'Порция',desc:'Бараньи рёбрышки с овощами и соусом',image:"assets/optimized/lamb-ribs.webp",photo:true},
  {id:37,name:'Куриный шашлык',cat:'Мангал',price:400,weight:'Порция',desc:'Куриное мясо, приготовленное на мангале',image:"assets/optimized/chicken-shashlik.webp",photo:true},
  {id:38,name:'Шашлык с овощами',cat:'Мангал',price:450,weight:'Порция',desc:'Шашлык с овощами, приготовленный на мангале',image:"assets/optimized/beef-shashlik.webp",photo:true},
  {id:39,name:'Люля-кебаб',cat:'Мангал',price:400,weight:'Порция',desc:'Люля-кебаб на мангале с овощами и соусом',image:"assets/optimized/lula-kebab.webp",photo:true},
  {id:40,name:'RC Cola',cat:'Напитки',price:200,weight:'1 л',desc:'Газированный напиток',image:"assets/optimized/rc-cola.webp",photo:true},
  {id:41,name:'Натахтари · вкус на выбор',cat:'Напитки',price:150,weight:'Бутылка',desc:'Лимонад Натахтари. Вкус уточняйте при заказе',image:"assets/optimized/natakhtari.webp",photo:true},
  {id:42,name:'Ассорти тортов',cat:'Торты',price:300,weight:'Кусочек',desc:'Выбор тортов уточняйте при заказе',image:"assets/optimized/assorted-cakes.webp",photo:true},
  {id:43,name:'Медовик',cat:'Торты',price:300,weight:'Кусочек',desc:'Медовый торт с нежным кремом',image:"assets/optimized/medovik.webp",photo:true},
  {id:44,name:'Турецкая пахлава',cat:'Торты',price:300,weight:'Порция',desc:'Турецкая пахлава',image:"assets/optimized/owner-desserts.webp",photo:true}
];
