create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  category text not null check (char_length(category) between 1 and 80),
  price integer not null check (price between 0 and 1000000),
  weight text not null default '' check (char_length(weight) <= 80),
  description text not null default '' check (char_length(description) <= 1000),
  image_url text not null default '' check (char_length(image_url) <= 2000),
  photo boolean not null default false,
  tag text check (tag is null or char_length(tag) <= 40),
  serving_note text check (serving_note is null or char_length(serving_note) <= 500),
  recipe text check (recipe is null or char_length(recipe) <= 2000),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null,
  order_type text not null check (order_type in ('Доставка', 'Самовывоз')),
  branch text not null,
  address text,
  comment text,
  total integer not null default 0 check (total between 0 and 1000000),
  status text not null default 'new' check (status in ('new', 'confirmed', 'completed', 'cancelled'))
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  menu_item_id bigint references public.menu_items (id) on delete set null,
  item_name text not null,
  unit_price integer not null check (unit_price between 0 and 1000000),
  quantity integer not null check (quantity between 1 and 9999),
  serving_note text
);
alter table public.order_items add column if not exists serving_note text;

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_phone_idx on public.orders (phone);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists menu_items_sort_order_idx on public.menu_items (sort_order, id);

create or replace function public.is_donishef_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_donishef_admin() from public;
grant execute on function public.is_donishef_admin() to authenticated;

alter table public.admin_users enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read menu" on public.menu_items;
create policy "Public can read menu"
  on public.menu_items for select to anon, authenticated
  using (true);

drop policy if exists "Admins manage menu" on public.menu_items;
create policy "Admins manage menu"
  on public.menu_items for all to authenticated
  using (public.is_donishef_admin())
  with check (public.is_donishef_admin());

drop policy if exists "Admins read orders" on public.orders;
create policy "Admins read orders"
  on public.orders for select to authenticated
  using (public.is_donishef_admin());

drop policy if exists "Admins update orders" on public.orders;
create policy "Admins update orders"
  on public.orders for update to authenticated
  using (public.is_donishef_admin())
  with check (public.is_donishef_admin());

drop policy if exists "Admins read order items" on public.order_items;
create policy "Admins read order items"
  on public.order_items for select to authenticated
  using (public.is_donishef_admin());

revoke all on table public.admin_users, public.menu_items, public.orders, public.order_items from public, anon, authenticated;
revoke all on sequence public.menu_items_id_seq from public, anon, authenticated;
grant select on public.menu_items to anon, authenticated;
grant insert, update, delete on public.menu_items to authenticated;
grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant usage, select on sequence public.menu_items_id_seq to authenticated;

create or replace function public.create_restaurant_order(
  p_customer_name text,
  p_phone text,
  p_order_type text,
  p_branch text,
  p_address text,
  p_comment text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_line jsonb;
  v_menu_item public.menu_items%rowtype;
  v_item_id bigint;
  v_quantity integer;
  v_total bigint := 0;
  v_line_count integer := 0;
begin
  if char_length(trim(coalesce(p_customer_name, ''))) not between 1 and 120 then
    raise exception 'Укажите имя длиной от 1 до 120 символов.';
  end if;
  if trim(coalesce(p_phone, '')) !~ '^\+?[0-9 ()-]{7,20}$' then
    raise exception 'Укажите корректный номер телефона.';
  end if;
  if p_order_type not in ('Доставка', 'Самовывоз') then
    raise exception 'Неизвестный способ получения заказа.';
  end if;
  if char_length(trim(coalesce(p_branch, ''))) not between 1 and 160 then
    raise exception 'Выберите филиал.';
  end if;
  if p_order_type = 'Доставка' and char_length(trim(coalesce(p_address, ''))) not between 3 and 300 then
    raise exception 'Для доставки укажите адрес.';
  end if;
  if char_length(coalesce(p_comment, '')) > 1000 then
    raise exception 'Комментарий слишком длинный.';
  end if;
  if coalesce(jsonb_typeof(p_items), '') <> 'array' then
    raise exception 'Некорректный список блюд.';
  end if;
  if jsonb_array_length(p_items) not between 1 and 30 then
    raise exception 'В заказе должно быть от 1 до 30 позиций.';
  end if;
  if (
    select count(*)
    from public.orders
    where phone = trim(p_phone)
      and created_at > now() - interval '1 hour'
  ) >= 20 then
    raise exception 'Слишком много заявок с этого номера. Попробуйте позже.';
  end if;

  insert into public.orders (customer_name, phone, order_type, branch, address, comment)
  values (
    trim(p_customer_name),
    trim(p_phone),
    p_order_type,
    trim(p_branch),
    nullif(trim(coalesce(p_address, '')), ''),
    nullif(trim(coalesce(p_comment, '')), '')
  )
  returning id into v_order_id;

  for v_line in select value from jsonb_array_elements(p_items) as lines(value)
  loop
    v_line_count := v_line_count + 1;
    if coalesce(v_line->>'id', '') !~ '^[0-9]{1,18}$'
      or coalesce(v_line->>'quantity', '') !~ '^[0-9]{1,4}$' then
      raise exception 'Некорректная позиция заказа.';
    end if;
    v_item_id := (v_line->>'id')::bigint;
    v_quantity := (v_line->>'quantity')::integer;
    if v_quantity not between 1 and 9999 then
      raise exception 'Некорректное количество позиции.';
    end if;

    select * into v_menu_item
    from public.menu_items
    where id = v_item_id;
    if not found then
      raise exception 'Одно из блюд больше недоступно. Обновите страницу и повторите заказ.';
    end if;

    v_total := v_total + v_menu_item.price::bigint * v_quantity;
    if v_total > 1000000 then
      raise exception 'Сумма заказа превышает допустимый предел.';
    end if;

    insert into public.order_items (order_id, menu_item_id, item_name, unit_price, quantity, serving_note)
    values (
      v_order_id,
      v_menu_item.id,
      v_menu_item.name,
      v_menu_item.price,
      v_quantity,
      coalesce(
        v_menu_item.serving_note,
        case when v_menu_item.category not in ('Напитки', 'Торты', 'Салаты', 'Гарниры', 'Детское меню')
          then 'ЛЕПЁШКА В ПОДАРОК К КАЖДОМУ БЛЮДУ'
          else null
        end
      )
    );
  end loop;

  if v_line_count <> jsonb_array_length(p_items) then
    raise exception 'Некорректное количество позиций заказа.';
  end if;
  update public.orders set total = v_total::integer where id = v_order_id;
  return jsonb_build_object(
    'id', v_order_id,
    'total', v_total,
    'items', (
      select jsonb_agg(jsonb_build_object(
        'name', item_name,
        'price', unit_price,
        'quantity', quantity,
        'serving_note', serving_note
      ) order by id)
      from public.order_items
      where order_id = v_order_id
    )
  );
end;
$$;

revoke all on function public.create_restaurant_order(text, text, text, text, text, text, jsonb) from public;
grant execute on function public.create_restaurant_order(text, text, text, text, text, text, jsonb) to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('menu-photos', 'menu-photos', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read menu photos" on storage.objects;
create policy "Public can read menu photos"
  on storage.objects for select to public
  using (bucket_id = 'menu-photos');

drop policy if exists "Admins upload menu photos" on storage.objects;
create policy "Admins upload menu photos"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'menu-photos' and public.is_donishef_admin());

drop policy if exists "Admins update menu photos" on storage.objects;
create policy "Admins update menu photos"
  on storage.objects for update to authenticated
  using (bucket_id = 'menu-photos' and public.is_donishef_admin())
  with check (bucket_id = 'menu-photos' and public.is_donishef_admin());
